#!/bin/bash
# vim: set ft=sh

set -e

cd diego-release/

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go install github.com/apcera/gnatsd
go install github.com/coreos/etcd
go install github.com/onsi/ginkgo/ginkgo

# pushd src/github.com/cloudfoundry-incubator/bbs/db/sqldb
#   ginkgo -p .
# popd

RUN_SQL_TESTS=true scripts/run-unit-tests


